// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: background.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canonicalJSON = `-- name: CanonicalJSON :one
SELECT $1::jsonb::text AS canonical
`

func (q *Queries) CanonicalJSON(ctx context.Context, dollar_1 []byte) (string, error) {
	row := q.db.QueryRow(ctx, canonicalJSON, dollar_1)
	var canonical string
	err := row.Scan(&canonical)
	return canonical, err
}

const countInboxDuplicates = `-- name: CountInboxDuplicates :one
SELECT count(*) FROM inbox WHERE consumer = $1 AND outcome LIKE 'duplicate%'
`

func (q *Queries) CountInboxDuplicates(ctx context.Context, consumer string) (int64, error) {
	row := q.db.QueryRow(ctx, countInboxDuplicates, consumer)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOverdueRetries = `-- name: CountOverdueRetries :one
SELECT count(*) FROM background_requests WHERE state = 'retry_scheduled' AND retry_at < $1
`

func (q *Queries) CountOverdueRetries(ctx context.Context, retryAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueRetries, retryAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByState = `-- name: CountRequestsByState :many
SELECT state, count(*) AS n FROM background_requests GROUP BY state
`

type CountRequestsByStateRow struct {
	State string
	N     int64
}

func (q *Queries) CountRequestsByState(ctx context.Context) ([]CountRequestsByStateRow, error) {
	rows, err := q.db.Query(ctx, countRequestsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRequestsByStateRow{}
	for rows.Next() {
		var i CountRequestsByStateRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrantState = `-- name: GetGrantState :one
SELECT tenant_id, state, expires_at FROM grants WHERE grant_id = $1 FOR SHARE
`

type GetGrantStateRow struct {
	TenantID  string
	State     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetGrantState(ctx context.Context, grantID string) (GetGrantStateRow, error) {
	row := q.db.QueryRow(ctx, getGrantState, grantID)
	var i GetGrantStateRow
	err := row.Scan(&i.TenantID, &i.State, &i.ExpiresAt)
	return i, err
}

const getLatestRequest = `-- name: GetLatestRequest :one
SELECT task_id, generation, task_kind, input_digest, input, state, worker_id, lease_until, attempt_count, result_ref, result_digest, failure_code, created_at, updated_at, tenant_id, revision, result_profile, effects, dispatch_id, authorization_ref, max_attempts, retry_at, correlation_id, completed_at FROM background_requests WHERE task_id = $1 ORDER BY generation DESC LIMIT 1
`

func (q *Queries) GetLatestRequest(ctx context.Context, taskID string) (BackgroundRequest, error) {
	row := q.db.QueryRow(ctx, getLatestRequest, taskID)
	var i BackgroundRequest
	err := row.Scan(
		&i.TaskID,
		&i.Generation,
		&i.TaskKind,
		&i.InputDigest,
		&i.Input,
		&i.State,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.Revision,
		&i.ResultProfile,
		&i.Effects,
		&i.DispatchID,
		&i.AuthorizationRef,
		&i.MaxAttempts,
		&i.RetryAt,
		&i.CorrelationID,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestRequestForUpdate = `-- name: GetLatestRequestForUpdate :one
SELECT task_id, generation, task_kind, input_digest, input, state, worker_id, lease_until, attempt_count, result_ref, result_digest, failure_code, created_at, updated_at, tenant_id, revision, result_profile, effects, dispatch_id, authorization_ref, max_attempts, retry_at, correlation_id, completed_at FROM background_requests WHERE task_id = $1 ORDER BY generation DESC LIMIT 1 FOR UPDATE
`

func (q *Queries) GetLatestRequestForUpdate(ctx context.Context, taskID string) (BackgroundRequest, error) {
	row := q.db.QueryRow(ctx, getLatestRequestForUpdate, taskID)
	var i BackgroundRequest
	err := row.Scan(
		&i.TaskID,
		&i.Generation,
		&i.TaskKind,
		&i.InputDigest,
		&i.Input,
		&i.State,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.Revision,
		&i.ResultProfile,
		&i.Effects,
		&i.DispatchID,
		&i.AuthorizationRef,
		&i.MaxAttempts,
		&i.RetryAt,
		&i.CorrelationID,
		&i.CompletedAt,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT task_id, generation, task_kind, input_digest, input, state, worker_id, lease_until, attempt_count, result_ref, result_digest, failure_code, created_at, updated_at, tenant_id, revision, result_profile, effects, dispatch_id, authorization_ref, max_attempts, retry_at, correlation_id, completed_at FROM background_requests WHERE task_id = $1 AND generation = $2
`

type GetRequestParams struct {
	TaskID     string
	Generation int64
}

func (q *Queries) GetRequest(ctx context.Context, arg GetRequestParams) (BackgroundRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, arg.TaskID, arg.Generation)
	var i BackgroundRequest
	err := row.Scan(
		&i.TaskID,
		&i.Generation,
		&i.TaskKind,
		&i.InputDigest,
		&i.Input,
		&i.State,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.Revision,
		&i.ResultProfile,
		&i.Effects,
		&i.DispatchID,
		&i.AuthorizationRef,
		&i.MaxAttempts,
		&i.RetryAt,
		&i.CorrelationID,
		&i.CompletedAt,
	)
	return i, err
}

const getRequestForUpdate = `-- name: GetRequestForUpdate :one

SELECT task_id, generation, task_kind, input_digest, input, state, worker_id, lease_until, attempt_count, result_ref, result_digest, failure_code, created_at, updated_at, tenant_id, revision, result_profile, effects, dispatch_id, authorization_ref, max_attempts, retry_at, correlation_id, completed_at FROM background_requests WHERE task_id = $1 AND generation = $2 FOR UPDATE
`

type GetRequestForUpdateParams struct {
	TaskID     string
	Generation int64
}

// Durable background requests of the MCP owner (DD-09 §1, migration 00002).
// Every mutation runs under the row lock of the generation; the outbox
// insert of the same transaction goes through the watermill-sql publisher.
func (q *Queries) GetRequestForUpdate(ctx context.Context, arg GetRequestForUpdateParams) (BackgroundRequest, error) {
	row := q.db.QueryRow(ctx, getRequestForUpdate, arg.TaskID, arg.Generation)
	var i BackgroundRequest
	err := row.Scan(
		&i.TaskID,
		&i.Generation,
		&i.TaskKind,
		&i.InputDigest,
		&i.Input,
		&i.State,
		&i.WorkerID,
		&i.LeaseUntil,
		&i.AttemptCount,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.Revision,
		&i.ResultProfile,
		&i.Effects,
		&i.DispatchID,
		&i.AuthorizationRef,
		&i.MaxAttempts,
		&i.RetryAt,
		&i.CorrelationID,
		&i.CompletedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO task_attempts (task_id, generation, ordinal, worker_id, leased_at, lease_until) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAttemptParams struct {
	TaskID     string
	Generation int64
	Ordinal    int32
	WorkerID   string
	LeasedAt   pgtype.Timestamptz
	LeaseUntil pgtype.Timestamptz
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.TaskID,
		arg.Generation,
		arg.Ordinal,
		arg.WorkerID,
		arg.LeasedAt,
		arg.LeaseUntil,
	)
	return err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO background_requests (
    task_id, generation, tenant_id, task_kind, input_digest, input, state, attempt_count, max_attempts,
    result_profile, effects, dispatch_id, authorization_ref, revision, correlation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, 0, $8, $9, $10, $11, $12, 1, $13)
`

type InsertRequestParams struct {
	TaskID           string
	Generation       int64
	TenantID         string
	TaskKind         string
	InputDigest      string
	Input            []byte
	State            string
	MaxAttempts      int32
	ResultProfile    string
	Effects          string
	DispatchID       *string
	AuthorizationRef string
	CorrelationID    string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.Exec(ctx, insertRequest,
		arg.TaskID,
		arg.Generation,
		arg.TenantID,
		arg.TaskKind,
		arg.InputDigest,
		arg.Input,
		arg.State,
		arg.MaxAttempts,
		arg.ResultProfile,
		arg.Effects,
		arg.DispatchID,
		arg.AuthorizationRef,
		arg.CorrelationID,
	)
	return err
}

const listAttempts = `-- name: ListAttempts :many
SELECT task_id, generation, ordinal, worker_id, leased_at, lease_until, outcome, submitted_at FROM task_attempts WHERE task_id = $1 AND generation = $2 ORDER BY ordinal
`

type ListAttemptsParams struct {
	TaskID     string
	Generation int64
}

func (q *Queries) ListAttempts(ctx context.Context, arg ListAttemptsParams) ([]TaskAttempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, arg.TaskID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAttempt{}
	for rows.Next() {
		var i TaskAttempt
		if err := rows.Scan(
			&i.TaskID,
			&i.Generation,
			&i.Ordinal,
			&i.WorkerID,
			&i.LeasedAt,
			&i.LeaseUntil,
			&i.Outcome,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredLeases = `-- name: ListExpiredLeases :many
SELECT task_id, generation FROM background_requests WHERE state = 'leased' AND lease_until < $1 ORDER BY lease_until LIMIT $2
`

type ListExpiredLeasesParams struct {
	LeaseUntil pgtype.Timestamptz
	Limit      int32
}

type ListExpiredLeasesRow struct {
	TaskID     string
	Generation int64
}

func (q *Queries) ListExpiredLeases(ctx context.Context, arg ListExpiredLeasesParams) ([]ListExpiredLeasesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredLeases, arg.LeaseUntil, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredLeasesRow{}
	for rows.Next() {
		var i ListExpiredLeasesRow
		if err := rows.Scan(&i.TaskID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestUnforwardedSeconds = `-- name: OldestUnforwardedSeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM (now() - min(created_at))), 0)::float8 AS seconds
FROM outbox
WHERE (transaction_id, "offset") > (
    SELECT COALESCE(max(last_processed_transaction_id), '0'::xid8), COALESCE(max(offset_acked), 0)
    FROM outbox_offsets WHERE consumer_group = $1
)
`

func (q *Queries) OldestUnforwardedSeconds(ctx context.Context, consumerGroup string) (float64, error) {
	row := q.db.QueryRow(ctx, oldestUnforwardedSeconds, consumerGroup)
	var seconds float64
	err := row.Scan(&seconds)
	return seconds, err
}

const setAttemptOutcome = `-- name: SetAttemptOutcome :exec
UPDATE task_attempts SET outcome = $4, submitted_at = $5 WHERE task_id = $1 AND generation = $2 AND ordinal = $3
`

type SetAttemptOutcomeParams struct {
	TaskID      string
	Generation  int64
	Ordinal     int32
	Outcome     *string
	SubmittedAt pgtype.Timestamptz
}

func (q *Queries) SetAttemptOutcome(ctx context.Context, arg SetAttemptOutcomeParams) error {
	_, err := q.db.Exec(ctx, setAttemptOutcome,
		arg.TaskID,
		arg.Generation,
		arg.Ordinal,
		arg.Outcome,
		arg.SubmittedAt,
	)
	return err
}

const updateRequest = `-- name: UpdateRequest :execrows
UPDATE background_requests SET
    state = $3, worker_id = $4, lease_until = $5, attempt_count = $6, retry_at = $7,
    result_ref = $8, result_digest = $9, failure_code = $10, revision = $11, completed_at = $12, updated_at = now()
WHERE task_id = $1 AND generation = $2 AND revision = $13
`

type UpdateRequestParams struct {
	TaskID           string
	Generation       int64
	State            string
	WorkerID         *string
	LeaseUntil       pgtype.Timestamptz
	AttemptCount     int32
	RetryAt          pgtype.Timestamptz
	ResultRef        *string
	ResultDigest     *string
	FailureCode      *string
	Revision         int64
	CompletedAt      pgtype.Timestamptz
	ExpectedRevision int64
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRequest,
		arg.TaskID,
		arg.Generation,
		arg.State,
		arg.WorkerID,
		arg.LeaseUntil,
		arg.AttemptCount,
		arg.RetryAt,
		arg.ResultRef,
		arg.ResultDigest,
		arg.FailureCode,
		arg.Revision,
		arg.CompletedAt,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
