// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: calls.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGrantForShare = `-- name: GetGrantForShare :one
SELECT grant_id, revision, tenant_id, subject_type, subject_id, server_id, descriptor_revision, descriptor_digest, methods, purpose, cost_cap_currency, cost_cap_amount, state, control_receipt_id, expires_at, command_id, request_digest, created_at, updated_at, canonical_resource, transport, protocol_version, issuer, audience, resource_selectors, prompt_selectors, data_class, policy_digest, policy_epoch, failure_code, registration_command_id, revocation_command_id, fenced_at, in_flight_calls, unknown_calls, control_state, revoked_at FROM grants WHERE grant_id = $1 FOR SHARE
`

func (q *Queries) GetGrantForShare(ctx context.Context, grantID string) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrantForShare, grantID)
	var i Grant
	err := row.Scan(
		&i.GrantID,
		&i.Revision,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.DescriptorDigest,
		&i.Methods,
		&i.Purpose,
		&i.CostCapCurrency,
		&i.CostCapAmount,
		&i.State,
		&i.ControlReceiptID,
		&i.ExpiresAt,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanonicalResource,
		&i.Transport,
		&i.ProtocolVersion,
		&i.Issuer,
		&i.Audience,
		&i.ResourceSelectors,
		&i.PromptSelectors,
		&i.DataClass,
		&i.PolicyDigest,
		&i.PolicyEpoch,
		&i.FailureCode,
		&i.RegistrationCommandID,
		&i.RevocationCommandID,
		&i.FencedAt,
		&i.InFlightCalls,
		&i.UnknownCalls,
		&i.ControlState,
		&i.RevokedAt,
	)
	return i, err
}

const getToolRequest = `-- name: GetToolRequest :one

SELECT call_id, tenant_id, grant_id, grant_revision, server_id, descriptor_revision, method, argument_ref, argument_digest, operation_id, attempt_id, state, control_dispatch_id, result_ref, result_digest, failure_code, command_id, request_digest, deadline, created_at, updated_at, instance_id, execution_epoch, arguments, descriptor_digest, protocol_version, transport, route, side_effecting, exposure_currency, exposure_amount, send_marker_at, observed_at, observation_sequence, usage_units, native_evidence, result FROM tool_requests WHERE call_id = $1
`

// Tool requests (P19). Every state change is a guarded update of the row
// under its lock; the send marker is committed before the single send.
func (q *Queries) GetToolRequest(ctx context.Context, callID string) (ToolRequest, error) {
	row := q.db.QueryRow(ctx, getToolRequest, callID)
	var i ToolRequest
	err := row.Scan(
		&i.CallID,
		&i.TenantID,
		&i.GrantID,
		&i.GrantRevision,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.Method,
		&i.ArgumentRef,
		&i.ArgumentDigest,
		&i.OperationID,
		&i.AttemptID,
		&i.State,
		&i.ControlDispatchID,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceID,
		&i.ExecutionEpoch,
		&i.Arguments,
		&i.DescriptorDigest,
		&i.ProtocolVersion,
		&i.Transport,
		&i.Route,
		&i.SideEffecting,
		&i.ExposureCurrency,
		&i.ExposureAmount,
		&i.SendMarkerAt,
		&i.ObservedAt,
		&i.ObservationSequence,
		&i.UsageUnits,
		&i.NativeEvidence,
		&i.Result,
	)
	return i, err
}

const getToolRequestByCommand = `-- name: GetToolRequestByCommand :one
SELECT call_id, tenant_id, grant_id, grant_revision, server_id, descriptor_revision, method, argument_ref, argument_digest, operation_id, attempt_id, state, control_dispatch_id, result_ref, result_digest, failure_code, command_id, request_digest, deadline, created_at, updated_at, instance_id, execution_epoch, arguments, descriptor_digest, protocol_version, transport, route, side_effecting, exposure_currency, exposure_amount, send_marker_at, observed_at, observation_sequence, usage_units, native_evidence, result FROM tool_requests WHERE tenant_id = $1 AND command_id = $2
`

type GetToolRequestByCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetToolRequestByCommand(ctx context.Context, arg GetToolRequestByCommandParams) (ToolRequest, error) {
	row := q.db.QueryRow(ctx, getToolRequestByCommand, arg.TenantID, arg.CommandID)
	var i ToolRequest
	err := row.Scan(
		&i.CallID,
		&i.TenantID,
		&i.GrantID,
		&i.GrantRevision,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.Method,
		&i.ArgumentRef,
		&i.ArgumentDigest,
		&i.OperationID,
		&i.AttemptID,
		&i.State,
		&i.ControlDispatchID,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceID,
		&i.ExecutionEpoch,
		&i.Arguments,
		&i.DescriptorDigest,
		&i.ProtocolVersion,
		&i.Transport,
		&i.Route,
		&i.SideEffecting,
		&i.ExposureCurrency,
		&i.ExposureAmount,
		&i.SendMarkerAt,
		&i.ObservedAt,
		&i.ObservationSequence,
		&i.UsageUnits,
		&i.NativeEvidence,
		&i.Result,
	)
	return i, err
}

const getToolRequestForUpdate = `-- name: GetToolRequestForUpdate :one
SELECT call_id, tenant_id, grant_id, grant_revision, server_id, descriptor_revision, method, argument_ref, argument_digest, operation_id, attempt_id, state, control_dispatch_id, result_ref, result_digest, failure_code, command_id, request_digest, deadline, created_at, updated_at, instance_id, execution_epoch, arguments, descriptor_digest, protocol_version, transport, route, side_effecting, exposure_currency, exposure_amount, send_marker_at, observed_at, observation_sequence, usage_units, native_evidence, result FROM tool_requests WHERE call_id = $1 FOR UPDATE
`

func (q *Queries) GetToolRequestForUpdate(ctx context.Context, callID string) (ToolRequest, error) {
	row := q.db.QueryRow(ctx, getToolRequestForUpdate, callID)
	var i ToolRequest
	err := row.Scan(
		&i.CallID,
		&i.TenantID,
		&i.GrantID,
		&i.GrantRevision,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.Method,
		&i.ArgumentRef,
		&i.ArgumentDigest,
		&i.OperationID,
		&i.AttemptID,
		&i.State,
		&i.ControlDispatchID,
		&i.ResultRef,
		&i.ResultDigest,
		&i.FailureCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceID,
		&i.ExecutionEpoch,
		&i.Arguments,
		&i.DescriptorDigest,
		&i.ProtocolVersion,
		&i.Transport,
		&i.Route,
		&i.SideEffecting,
		&i.ExposureCurrency,
		&i.ExposureAmount,
		&i.SendMarkerAt,
		&i.ObservedAt,
		&i.ObservationSequence,
		&i.UsageUnits,
		&i.NativeEvidence,
		&i.Result,
	)
	return i, err
}

const hasUnknownToolRequest = `-- name: HasUnknownToolRequest :one
SELECT EXISTS (SELECT 1 FROM tool_requests WHERE tenant_id = $1 AND server_id = $2 AND state = 'unknown')
`

type HasUnknownToolRequestParams struct {
	TenantID string
	ServerID string
}

func (q *Queries) HasUnknownToolRequest(ctx context.Context, arg HasUnknownToolRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnknownToolRequest, arg.TenantID, arg.ServerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertToolRequest = `-- name: InsertToolRequest :exec
INSERT INTO tool_requests (call_id, tenant_id, grant_id, grant_revision, server_id, descriptor_revision, method, argument_ref, argument_digest,
    operation_id, attempt_id, state, command_id, request_digest, deadline, instance_id, execution_epoch, arguments, descriptor_digest,
    protocol_version, transport, route, side_effecting, exposure_currency, exposure_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'accepted', $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)
`

type InsertToolRequestParams struct {
	CallID             string
	TenantID           string
	GrantID            string
	GrantRevision      int64
	ServerID           string
	DescriptorRevision int64
	Method             string
	ArgumentRef        string
	ArgumentDigest     string
	OperationID        *string
	AttemptID          *string
	CommandID          string
	RequestDigest      string
	Deadline           pgtype.Timestamptz
	InstanceID         string
	ExecutionEpoch     int64
	Arguments          []byte
	DescriptorDigest   string
	ProtocolVersion    string
	Transport          string
	Route              string
	SideEffecting      bool
	ExposureCurrency   string
	ExposureAmount     int64
}

func (q *Queries) InsertToolRequest(ctx context.Context, arg InsertToolRequestParams) error {
	_, err := q.db.Exec(ctx, insertToolRequest,
		arg.CallID,
		arg.TenantID,
		arg.GrantID,
		arg.GrantRevision,
		arg.ServerID,
		arg.DescriptorRevision,
		arg.Method,
		arg.ArgumentRef,
		arg.ArgumentDigest,
		arg.OperationID,
		arg.AttemptID,
		arg.CommandID,
		arg.RequestDigest,
		arg.Deadline,
		arg.InstanceID,
		arg.ExecutionEpoch,
		arg.Arguments,
		arg.DescriptorDigest,
		arg.ProtocolVersion,
		arg.Transport,
		arg.Route,
		arg.SideEffecting,
		arg.ExposureCurrency,
		arg.ExposureAmount,
	)
	return err
}

const listOpenToolRequests = `-- name: ListOpenToolRequests :many
SELECT call_id, tenant_id, grant_id, grant_revision, server_id, descriptor_revision, method, argument_ref, argument_digest, operation_id, attempt_id, state, control_dispatch_id, result_ref, result_digest, failure_code, command_id, request_digest, deadline, created_at, updated_at, instance_id, execution_epoch, arguments, descriptor_digest, protocol_version, transport, route, side_effecting, exposure_currency, exposure_amount, send_marker_at, observed_at, observation_sequence, usage_units, native_evidence, result FROM tool_requests
WHERE (state IN ('accepted', 'admitted', 'sent', 'unknown') OR (observed_at IS NULL AND control_dispatch_id IS NOT NULL AND state IN ('succeeded', 'failed', 'canceled')))
  AND updated_at < now() - make_interval(secs => $2::float8)
ORDER BY updated_at LIMIT $1
`

type ListOpenToolRequestsParams struct {
	Limit      int32
	AgeSeconds float64
}

func (q *Queries) ListOpenToolRequests(ctx context.Context, arg ListOpenToolRequestsParams) ([]ToolRequest, error) {
	rows, err := q.db.Query(ctx, listOpenToolRequests, arg.Limit, arg.AgeSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolRequest{}
	for rows.Next() {
		var i ToolRequest
		if err := rows.Scan(
			&i.CallID,
			&i.TenantID,
			&i.GrantID,
			&i.GrantRevision,
			&i.ServerID,
			&i.DescriptorRevision,
			&i.Method,
			&i.ArgumentRef,
			&i.ArgumentDigest,
			&i.OperationID,
			&i.AttemptID,
			&i.State,
			&i.ControlDispatchID,
			&i.ResultRef,
			&i.ResultDigest,
			&i.FailureCode,
			&i.CommandID,
			&i.RequestDigest,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstanceID,
			&i.ExecutionEpoch,
			&i.Arguments,
			&i.DescriptorDigest,
			&i.ProtocolVersion,
			&i.Transport,
			&i.Route,
			&i.SideEffecting,
			&i.ExposureCurrency,
			&i.ExposureAmount,
			&i.SendMarkerAt,
			&i.ObservedAt,
			&i.ObservationSequence,
			&i.UsageUnits,
			&i.NativeEvidence,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setToolRequestAdmission = `-- name: SetToolRequestAdmission :execrows
UPDATE tool_requests SET state = $2, control_dispatch_id = $3, failure_code = $4, updated_at = now()
WHERE call_id = $1 AND state = 'accepted'
`

type SetToolRequestAdmissionParams struct {
	CallID            string
	State             string
	ControlDispatchID *string
	FailureCode       *string
}

func (q *Queries) SetToolRequestAdmission(ctx context.Context, arg SetToolRequestAdmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setToolRequestAdmission,
		arg.CallID,
		arg.State,
		arg.ControlDispatchID,
		arg.FailureCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setToolRequestMarker = `-- name: SetToolRequestMarker :execrows
UPDATE tool_requests SET state = 'sent', send_marker_at = now(), updated_at = now()
WHERE call_id = $1 AND state = 'admitted' AND send_marker_at IS NULL
`

func (q *Queries) SetToolRequestMarker(ctx context.Context, callID string) (int64, error) {
	result, err := q.db.Exec(ctx, setToolRequestMarker, callID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setToolRequestObserved = `-- name: SetToolRequestObserved :exec
UPDATE tool_requests SET observed_at = now(), observation_sequence = observation_sequence + 1, updated_at = now()
WHERE call_id = $1 AND observation_sequence = $2
`

type SetToolRequestObservedParams struct {
	CallID              string
	ObservationSequence int64
}

func (q *Queries) SetToolRequestObserved(ctx context.Context, arg SetToolRequestObservedParams) error {
	_, err := q.db.Exec(ctx, setToolRequestObserved, arg.CallID, arg.ObservationSequence)
	return err
}

const setToolRequestOutcome = `-- name: SetToolRequestOutcome :execrows
UPDATE tool_requests SET state = $2, failure_code = $3, result = $4, result_digest = $5, result_ref = $6, native_evidence = $7, usage_units = $8,
    updated_at = now()
WHERE call_id = $1 AND state = ANY($9::text[])
`

type SetToolRequestOutcomeParams struct {
	CallID         string
	State          string
	FailureCode    *string
	Result         []byte
	ResultDigest   *string
	ResultRef      *string
	NativeEvidence []byte
	UsageUnits     *int64
	Expected       []string
}

func (q *Queries) SetToolRequestOutcome(ctx context.Context, arg SetToolRequestOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setToolRequestOutcome,
		arg.CallID,
		arg.State,
		arg.FailureCode,
		arg.Result,
		arg.ResultDigest,
		arg.ResultRef,
		arg.NativeEvidence,
		arg.UsageUnits,
		arg.Expected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
