// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenToolRequests = `-- name: CountOpenToolRequests :one
SELECT count(*)::bigint FROM tool_requests WHERE grant_id = $1 AND grant_revision = $2 AND state IN ('accepted', 'admitted', 'sent', 'unknown')
`

type CountOpenToolRequestsParams struct {
	GrantID       string
	GrantRevision int64
}

func (q *Queries) CountOpenToolRequests(ctx context.Context, arg CountOpenToolRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenToolRequests, arg.GrantID, arg.GrantRevision)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCatalogCommand = `-- name: GetCatalogCommand :one
SELECT tenant_id, command_id, command_kind, request_digest, server_id, revision, created_at FROM catalog_commands WHERE tenant_id = $1 AND command_id = $2
`

type GetCatalogCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetCatalogCommand(ctx context.Context, arg GetCatalogCommandParams) (CatalogCommand, error) {
	row := q.db.QueryRow(ctx, getCatalogCommand, arg.TenantID, arg.CommandID)
	var i CatalogCommand
	err := row.Scan(
		&i.TenantID,
		&i.CommandID,
		&i.CommandKind,
		&i.RequestDigest,
		&i.ServerID,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const getDescriptor = `-- name: GetDescriptor :one
SELECT server_id, revision, protocol_version, provenance, descriptor_digest, tools, state, command_id, request_digest, created_at, updated_at, server_name, server_version, resources, prompts, resources_digest, prompts_digest, data_class, network_scope, licenses, issuer, revision_evidence, connection_ref, discovered_by, reviewer, review_id FROM descriptors WHERE server_id = $1 AND revision = $2
`

type GetDescriptorParams struct {
	ServerID string
	Revision int64
}

func (q *Queries) GetDescriptor(ctx context.Context, arg GetDescriptorParams) (Descriptor, error) {
	row := q.db.QueryRow(ctx, getDescriptor, arg.ServerID, arg.Revision)
	var i Descriptor
	err := row.Scan(
		&i.ServerID,
		&i.Revision,
		&i.ProtocolVersion,
		&i.Provenance,
		&i.DescriptorDigest,
		&i.Tools,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServerName,
		&i.ServerVersion,
		&i.Resources,
		&i.Prompts,
		&i.ResourcesDigest,
		&i.PromptsDigest,
		&i.DataClass,
		&i.NetworkScope,
		&i.Licenses,
		&i.Issuer,
		&i.RevisionEvidence,
		&i.ConnectionRef,
		&i.DiscoveredBy,
		&i.Reviewer,
		&i.ReviewID,
	)
	return i, err
}

const getDescriptorByDigest = `-- name: GetDescriptorByDigest :one
SELECT server_id, revision, protocol_version, provenance, descriptor_digest, tools, state, command_id, request_digest, created_at, updated_at, server_name, server_version, resources, prompts, resources_digest, prompts_digest, data_class, network_scope, licenses, issuer, revision_evidence, connection_ref, discovered_by, reviewer, review_id FROM descriptors WHERE server_id = $1 AND descriptor_digest = $2
`

type GetDescriptorByDigestParams struct {
	ServerID         string
	DescriptorDigest string
}

func (q *Queries) GetDescriptorByDigest(ctx context.Context, arg GetDescriptorByDigestParams) (Descriptor, error) {
	row := q.db.QueryRow(ctx, getDescriptorByDigest, arg.ServerID, arg.DescriptorDigest)
	var i Descriptor
	err := row.Scan(
		&i.ServerID,
		&i.Revision,
		&i.ProtocolVersion,
		&i.Provenance,
		&i.DescriptorDigest,
		&i.Tools,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServerName,
		&i.ServerVersion,
		&i.Resources,
		&i.Prompts,
		&i.ResourcesDigest,
		&i.PromptsDigest,
		&i.DataClass,
		&i.NetworkScope,
		&i.Licenses,
		&i.Issuer,
		&i.RevisionEvidence,
		&i.ConnectionRef,
		&i.DiscoveredBy,
		&i.Reviewer,
		&i.ReviewID,
	)
	return i, err
}

const getDescriptorForUpdate = `-- name: GetDescriptorForUpdate :one
SELECT server_id, revision, protocol_version, provenance, descriptor_digest, tools, state, command_id, request_digest, created_at, updated_at, server_name, server_version, resources, prompts, resources_digest, prompts_digest, data_class, network_scope, licenses, issuer, revision_evidence, connection_ref, discovered_by, reviewer, review_id FROM descriptors WHERE server_id = $1 AND revision = $2 FOR UPDATE
`

type GetDescriptorForUpdateParams struct {
	ServerID string
	Revision int64
}

func (q *Queries) GetDescriptorForUpdate(ctx context.Context, arg GetDescriptorForUpdateParams) (Descriptor, error) {
	row := q.db.QueryRow(ctx, getDescriptorForUpdate, arg.ServerID, arg.Revision)
	var i Descriptor
	err := row.Scan(
		&i.ServerID,
		&i.Revision,
		&i.ProtocolVersion,
		&i.Provenance,
		&i.DescriptorDigest,
		&i.Tools,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServerName,
		&i.ServerVersion,
		&i.Resources,
		&i.Prompts,
		&i.ResourcesDigest,
		&i.PromptsDigest,
		&i.DataClass,
		&i.NetworkScope,
		&i.Licenses,
		&i.Issuer,
		&i.RevisionEvidence,
		&i.ConnectionRef,
		&i.DiscoveredBy,
		&i.Reviewer,
		&i.ReviewID,
	)
	return i, err
}

const getGrant = `-- name: GetGrant :one
SELECT grant_id, revision, tenant_id, subject_type, subject_id, server_id, descriptor_revision, descriptor_digest, methods, purpose, cost_cap_currency, cost_cap_amount, state, control_receipt_id, expires_at, command_id, request_digest, created_at, updated_at, canonical_resource, transport, protocol_version, issuer, audience, resource_selectors, prompt_selectors, data_class, policy_digest, policy_epoch, failure_code, registration_command_id, revocation_command_id, fenced_at, in_flight_calls, unknown_calls, control_state, revoked_at FROM grants WHERE grant_id = $1
`

func (q *Queries) GetGrant(ctx context.Context, grantID string) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrant, grantID)
	var i Grant
	err := row.Scan(
		&i.GrantID,
		&i.Revision,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.DescriptorDigest,
		&i.Methods,
		&i.Purpose,
		&i.CostCapCurrency,
		&i.CostCapAmount,
		&i.State,
		&i.ControlReceiptID,
		&i.ExpiresAt,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanonicalResource,
		&i.Transport,
		&i.ProtocolVersion,
		&i.Issuer,
		&i.Audience,
		&i.ResourceSelectors,
		&i.PromptSelectors,
		&i.DataClass,
		&i.PolicyDigest,
		&i.PolicyEpoch,
		&i.FailureCode,
		&i.RegistrationCommandID,
		&i.RevocationCommandID,
		&i.FencedAt,
		&i.InFlightCalls,
		&i.UnknownCalls,
		&i.ControlState,
		&i.RevokedAt,
	)
	return i, err
}

const getGrantByCommand = `-- name: GetGrantByCommand :one
SELECT grant_id, revision, tenant_id, subject_type, subject_id, server_id, descriptor_revision, descriptor_digest, methods, purpose, cost_cap_currency, cost_cap_amount, state, control_receipt_id, expires_at, command_id, request_digest, created_at, updated_at, canonical_resource, transport, protocol_version, issuer, audience, resource_selectors, prompt_selectors, data_class, policy_digest, policy_epoch, failure_code, registration_command_id, revocation_command_id, fenced_at, in_flight_calls, unknown_calls, control_state, revoked_at FROM grants WHERE tenant_id = $1 AND command_id = $2
`

type GetGrantByCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetGrantByCommand(ctx context.Context, arg GetGrantByCommandParams) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrantByCommand, arg.TenantID, arg.CommandID)
	var i Grant
	err := row.Scan(
		&i.GrantID,
		&i.Revision,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.DescriptorDigest,
		&i.Methods,
		&i.Purpose,
		&i.CostCapCurrency,
		&i.CostCapAmount,
		&i.State,
		&i.ControlReceiptID,
		&i.ExpiresAt,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanonicalResource,
		&i.Transport,
		&i.ProtocolVersion,
		&i.Issuer,
		&i.Audience,
		&i.ResourceSelectors,
		&i.PromptSelectors,
		&i.DataClass,
		&i.PolicyDigest,
		&i.PolicyEpoch,
		&i.FailureCode,
		&i.RegistrationCommandID,
		&i.RevocationCommandID,
		&i.FencedAt,
		&i.InFlightCalls,
		&i.UnknownCalls,
		&i.ControlState,
		&i.RevokedAt,
	)
	return i, err
}

const getGrantDecisionByCommand = `-- name: GetGrantDecisionByCommand :one
SELECT decision_id, grant_id, from_revision, to_revision, decision, decider, reason_code, command_id, request_digest, decided_at, tenant_id FROM grant_decisions WHERE tenant_id = $1 AND command_id = $2 AND decision = $3
`

type GetGrantDecisionByCommandParams struct {
	TenantID  string
	CommandID string
	Decision  string
}

func (q *Queries) GetGrantDecisionByCommand(ctx context.Context, arg GetGrantDecisionByCommandParams) (GrantDecision, error) {
	row := q.db.QueryRow(ctx, getGrantDecisionByCommand, arg.TenantID, arg.CommandID, arg.Decision)
	var i GrantDecision
	err := row.Scan(
		&i.DecisionID,
		&i.GrantID,
		&i.FromRevision,
		&i.ToRevision,
		&i.Decision,
		&i.Decider,
		&i.ReasonCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.DecidedAt,
		&i.TenantID,
	)
	return i, err
}

const getGrantForUpdate = `-- name: GetGrantForUpdate :one
SELECT grant_id, revision, tenant_id, subject_type, subject_id, server_id, descriptor_revision, descriptor_digest, methods, purpose, cost_cap_currency, cost_cap_amount, state, control_receipt_id, expires_at, command_id, request_digest, created_at, updated_at, canonical_resource, transport, protocol_version, issuer, audience, resource_selectors, prompt_selectors, data_class, policy_digest, policy_epoch, failure_code, registration_command_id, revocation_command_id, fenced_at, in_flight_calls, unknown_calls, control_state, revoked_at FROM grants WHERE grant_id = $1 FOR UPDATE
`

func (q *Queries) GetGrantForUpdate(ctx context.Context, grantID string) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrantForUpdate, grantID)
	var i Grant
	err := row.Scan(
		&i.GrantID,
		&i.Revision,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.ServerID,
		&i.DescriptorRevision,
		&i.DescriptorDigest,
		&i.Methods,
		&i.Purpose,
		&i.CostCapCurrency,
		&i.CostCapAmount,
		&i.State,
		&i.ControlReceiptID,
		&i.ExpiresAt,
		&i.CommandID,
		&i.RequestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanonicalResource,
		&i.Transport,
		&i.ProtocolVersion,
		&i.Issuer,
		&i.Audience,
		&i.ResourceSelectors,
		&i.PromptSelectors,
		&i.DataClass,
		&i.PolicyDigest,
		&i.PolicyEpoch,
		&i.FailureCode,
		&i.RegistrationCommandID,
		&i.RevocationCommandID,
		&i.FencedAt,
		&i.InFlightCalls,
		&i.UnknownCalls,
		&i.ControlState,
		&i.RevokedAt,
	)
	return i, err
}

const getServer = `-- name: GetServer :one
SELECT server_id, tenant_id, canonical_resource, transport, current_revision, created_at FROM servers WHERE server_id = $1
`

func (q *Queries) GetServer(ctx context.Context, serverID string) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, serverID)
	var i Server
	err := row.Scan(
		&i.ServerID,
		&i.TenantID,
		&i.CanonicalResource,
		&i.Transport,
		&i.CurrentRevision,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByResourceForUpdate = `-- name: GetServerByResourceForUpdate :one

SELECT server_id, tenant_id, canonical_resource, transport, current_revision, created_at FROM servers WHERE tenant_id = $1 AND canonical_resource = $2 FOR UPDATE
`

type GetServerByResourceForUpdateParams struct {
	TenantID          string
	CanonicalResource string
}

// The private catalog and the grant barrier (DD-08 §1/§2, migration 00003).
// Catalog and grant mutations run under the row lock of their server,
// descriptor or grant; every decision row is append-only; the outbox
// insert of the same transaction goes through the watermill-sql publisher.
func (q *Queries) GetServerByResourceForUpdate(ctx context.Context, arg GetServerByResourceForUpdateParams) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByResourceForUpdate, arg.TenantID, arg.CanonicalResource)
	var i Server
	err := row.Scan(
		&i.ServerID,
		&i.TenantID,
		&i.CanonicalResource,
		&i.Transport,
		&i.CurrentRevision,
		&i.CreatedAt,
	)
	return i, err
}

const insertCatalogCommand = `-- name: InsertCatalogCommand :exec
INSERT INTO catalog_commands (tenant_id, command_id, command_kind, request_digest, server_id, revision) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCatalogCommandParams struct {
	TenantID      string
	CommandID     string
	CommandKind   string
	RequestDigest string
	ServerID      string
	Revision      int64
}

func (q *Queries) InsertCatalogCommand(ctx context.Context, arg InsertCatalogCommandParams) error {
	_, err := q.db.Exec(ctx, insertCatalogCommand,
		arg.TenantID,
		arg.CommandID,
		arg.CommandKind,
		arg.RequestDigest,
		arg.ServerID,
		arg.Revision,
	)
	return err
}

const insertDescriptor = `-- name: InsertDescriptor :exec
INSERT INTO descriptors (server_id, revision, protocol_version, provenance, descriptor_digest, tools, state, command_id, request_digest,
    server_name, server_version, resources, prompts, resources_digest, prompts_digest, data_class, network_scope, licenses, issuer,
    revision_evidence, connection_ref, discovered_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
`

type InsertDescriptorParams struct {
	ServerID         string
	Revision         int64
	ProtocolVersion  string
	Provenance       string
	DescriptorDigest string
	Tools            []byte
	State            string
	CommandID        string
	RequestDigest    string
	ServerName       string
	ServerVersion    string
	Resources        []byte
	Prompts          []byte
	ResourcesDigest  string
	PromptsDigest    string
	DataClass        string
	NetworkScope     []string
	Licenses         []string
	Issuer           string
	RevisionEvidence string
	ConnectionRef    string
	DiscoveredBy     string
}

func (q *Queries) InsertDescriptor(ctx context.Context, arg InsertDescriptorParams) error {
	_, err := q.db.Exec(ctx, insertDescriptor,
		arg.ServerID,
		arg.Revision,
		arg.ProtocolVersion,
		arg.Provenance,
		arg.DescriptorDigest,
		arg.Tools,
		arg.State,
		arg.CommandID,
		arg.RequestDigest,
		arg.ServerName,
		arg.ServerVersion,
		arg.Resources,
		arg.Prompts,
		arg.ResourcesDigest,
		arg.PromptsDigest,
		arg.DataClass,
		arg.NetworkScope,
		arg.Licenses,
		arg.Issuer,
		arg.RevisionEvidence,
		arg.ConnectionRef,
		arg.DiscoveredBy,
	)
	return err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO grants (grant_id, revision, tenant_id, subject_type, subject_id, server_id, descriptor_revision, descriptor_digest, methods, purpose,
    cost_cap_currency, cost_cap_amount, state, expires_at, command_id, request_digest, canonical_resource, transport, protocol_version, issuer,
    audience, resource_selectors, prompt_selectors, data_class, policy_digest, registration_command_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
`

type InsertGrantParams struct {
	GrantID               string
	Revision              int64
	TenantID              string
	SubjectType           string
	SubjectID             string
	ServerID              string
	DescriptorRevision    int64
	DescriptorDigest      string
	Methods               []string
	Purpose               string
	CostCapCurrency       string
	CostCapAmount         int64
	State                 string
	ExpiresAt             pgtype.Timestamptz
	CommandID             string
	RequestDigest         string
	CanonicalResource     string
	Transport             string
	ProtocolVersion       string
	Issuer                string
	Audience              string
	ResourceSelectors     []string
	PromptSelectors       []string
	DataClass             string
	PolicyDigest          string
	RegistrationCommandID string
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.GrantID,
		arg.Revision,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.ServerID,
		arg.DescriptorRevision,
		arg.DescriptorDigest,
		arg.Methods,
		arg.Purpose,
		arg.CostCapCurrency,
		arg.CostCapAmount,
		arg.State,
		arg.ExpiresAt,
		arg.CommandID,
		arg.RequestDigest,
		arg.CanonicalResource,
		arg.Transport,
		arg.ProtocolVersion,
		arg.Issuer,
		arg.Audience,
		arg.ResourceSelectors,
		arg.PromptSelectors,
		arg.DataClass,
		arg.PolicyDigest,
		arg.RegistrationCommandID,
	)
	return err
}

const insertGrantDecision = `-- name: InsertGrantDecision :exec
INSERT INTO grant_decisions (decision_id, grant_id, from_revision, to_revision, decision, decider, reason_code, command_id, request_digest, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertGrantDecisionParams struct {
	DecisionID    string
	GrantID       string
	FromRevision  int64
	ToRevision    int64
	Decision      string
	Decider       string
	ReasonCode    *string
	CommandID     string
	RequestDigest string
	TenantID      string
}

func (q *Queries) InsertGrantDecision(ctx context.Context, arg InsertGrantDecisionParams) error {
	_, err := q.db.Exec(ctx, insertGrantDecision,
		arg.DecisionID,
		arg.GrantID,
		arg.FromRevision,
		arg.ToRevision,
		arg.Decision,
		arg.Decider,
		arg.ReasonCode,
		arg.CommandID,
		arg.RequestDigest,
		arg.TenantID,
	)
	return err
}

const insertReview = `-- name: InsertReview :exec
INSERT INTO reviews (review_id, server_id, revision, descriptor_digest, reviewer, decision, reason_code, command_id, request_digest, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertReviewParams struct {
	ReviewID         string
	ServerID         string
	Revision         int64
	DescriptorDigest string
	Reviewer         string
	Decision         string
	ReasonCode       *string
	CommandID        string
	RequestDigest    string
	TenantID         string
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) error {
	_, err := q.db.Exec(ctx, insertReview,
		arg.ReviewID,
		arg.ServerID,
		arg.Revision,
		arg.DescriptorDigest,
		arg.Reviewer,
		arg.Decision,
		arg.ReasonCode,
		arg.CommandID,
		arg.RequestDigest,
		arg.TenantID,
	)
	return err
}

const insertServer = `-- name: InsertServer :exec
INSERT INTO servers (server_id, tenant_id, canonical_resource, transport, current_revision) VALUES ($1, $2, $3, $4, 0)
`

type InsertServerParams struct {
	ServerID          string
	TenantID          string
	CanonicalResource string
	Transport         string
}

func (q *Queries) InsertServer(ctx context.Context, arg InsertServerParams) error {
	_, err := q.db.Exec(ctx, insertServer,
		arg.ServerID,
		arg.TenantID,
		arg.CanonicalResource,
		arg.Transport,
	)
	return err
}

const listDescriptors = `-- name: ListDescriptors :many
SELECT d.server_id, d.revision, d.protocol_version, d.provenance, d.descriptor_digest, d.tools, d.state, d.command_id, d.request_digest, d.created_at, d.updated_at, d.server_name, d.server_version, d.resources, d.prompts, d.resources_digest, d.prompts_digest, d.data_class, d.network_scope, d.licenses, d.issuer, d.revision_evidence, d.connection_ref, d.discovered_by, d.reviewer, d.review_id FROM descriptors d JOIN servers s ON s.server_id = d.server_id
WHERE s.tenant_id = $1 AND ($2::text = '' OR d.state = $2::text)
  AND ($3::boolean OR d.state IN ('approved', 'disabled'))
  AND (d.server_id, d.revision) > ($4::text, $5::bigint)
ORDER BY d.server_id, d.revision LIMIT $6
`

type ListDescriptorsParams struct {
	TenantID       string
	State          string
	IncludePending bool
	AfterServer    string
	AfterRevision  int64
	PageLimit      int32
}

func (q *Queries) ListDescriptors(ctx context.Context, arg ListDescriptorsParams) ([]Descriptor, error) {
	rows, err := q.db.Query(ctx, listDescriptors,
		arg.TenantID,
		arg.State,
		arg.IncludePending,
		arg.AfterServer,
		arg.AfterRevision,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Descriptor{}
	for rows.Next() {
		var i Descriptor
		if err := rows.Scan(
			&i.ServerID,
			&i.Revision,
			&i.ProtocolVersion,
			&i.Provenance,
			&i.DescriptorDigest,
			&i.Tools,
			&i.State,
			&i.CommandID,
			&i.RequestDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServerName,
			&i.ServerVersion,
			&i.Resources,
			&i.Prompts,
			&i.ResourcesDigest,
			&i.PromptsDigest,
			&i.DataClass,
			&i.NetworkScope,
			&i.Licenses,
			&i.Issuer,
			&i.RevisionEvidence,
			&i.ConnectionRef,
			&i.DiscoveredBy,
			&i.Reviewer,
			&i.ReviewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredGrants = `-- name: ListExpiredGrants :many
SELECT grant_id FROM grants WHERE state = 'active' AND expires_at IS NOT NULL AND expires_at <= $1 ORDER BY expires_at LIMIT $2
`

type ListExpiredGrantsParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListExpiredGrants(ctx context.Context, arg ListExpiredGrantsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredGrants, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var grant_id string
		if err := rows.Scan(&grant_id); err != nil {
			return nil, err
		}
		items = append(items, grant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT grant_id, revision, tenant_id, subject_type, subject_id, server_id, descriptor_revision, descriptor_digest, methods, purpose, cost_cap_currency, cost_cap_amount, state, control_receipt_id, expires_at, command_id, request_digest, created_at, updated_at, canonical_resource, transport, protocol_version, issuer, audience, resource_selectors, prompt_selectors, data_class, policy_digest, policy_epoch, failure_code, registration_command_id, revocation_command_id, fenced_at, in_flight_calls, unknown_calls, control_state, revoked_at FROM grants
WHERE tenant_id = $1 AND ($2::text = '' OR state = $2::text)
  AND ($3::boolean OR subject_type = 'tenant'
       OR (subject_type = 'project' AND subject_id = $4::text)
       OR (subject_type = 'actor' AND subject_id = $5::text))
  AND grant_id > $6::text
ORDER BY grant_id LIMIT $7
`

type ListGrantsParams struct {
	TenantID   string
	State      string
	ReadAll    bool
	ProjectID  string
	ActorID    string
	AfterGrant string
	PageLimit  int32
}

func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([]Grant, error) {
	rows, err := q.db.Query(ctx, listGrants,
		arg.TenantID,
		arg.State,
		arg.ReadAll,
		arg.ProjectID,
		arg.ActorID,
		arg.AfterGrant,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grant{}
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.GrantID,
			&i.Revision,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.ServerID,
			&i.DescriptorRevision,
			&i.DescriptorDigest,
			&i.Methods,
			&i.Purpose,
			&i.CostCapCurrency,
			&i.CostCapAmount,
			&i.State,
			&i.ControlReceiptID,
			&i.ExpiresAt,
			&i.CommandID,
			&i.RequestDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanonicalResource,
			&i.Transport,
			&i.ProtocolVersion,
			&i.Issuer,
			&i.Audience,
			&i.ResourceSelectors,
			&i.PromptSelectors,
			&i.DataClass,
			&i.PolicyDigest,
			&i.PolicyEpoch,
			&i.FailureCode,
			&i.RegistrationCommandID,
			&i.RevocationCommandID,
			&i.FencedAt,
			&i.InFlightCalls,
			&i.UnknownCalls,
			&i.ControlState,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsOfDescriptor = `-- name: ListGrantsOfDescriptor :many
SELECT grant_id FROM grants WHERE server_id = $1 AND descriptor_revision = $2 AND state IN ('pending', 'active') ORDER BY grant_id
`

type ListGrantsOfDescriptorParams struct {
	ServerID           string
	DescriptorRevision int64
}

func (q *Queries) ListGrantsOfDescriptor(ctx context.Context, arg ListGrantsOfDescriptorParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGrantsOfDescriptor, arg.ServerID, arg.DescriptorRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var grant_id string
		if err := rows.Scan(&grant_id); err != nil {
			return nil, err
		}
		items = append(items, grant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBarriers = `-- name: ListOpenBarriers :many
SELECT grant_id FROM grants WHERE state IN ('pending', 'revoking') AND updated_at <= now() - make_interval(secs => $1::float8)
ORDER BY updated_at LIMIT $2
`

type ListOpenBarriersParams struct {
	AgeSeconds float64
	PageLimit  int32
}

func (q *Queries) ListOpenBarriers(ctx context.Context, arg ListOpenBarriersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listOpenBarriers, arg.AgeSeconds, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var grant_id string
		if err := rows.Scan(&grant_id); err != nil {
			return nil, err
		}
		items = append(items, grant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerRevision = `-- name: SetServerRevision :exec
UPDATE servers SET current_revision = $2 WHERE server_id = $1
`

type SetServerRevisionParams struct {
	ServerID        string
	CurrentRevision int64
}

func (q *Queries) SetServerRevision(ctx context.Context, arg SetServerRevisionParams) error {
	_, err := q.db.Exec(ctx, setServerRevision, arg.ServerID, arg.CurrentRevision)
	return err
}

const updateDescriptorState = `-- name: UpdateDescriptorState :exec
UPDATE descriptors SET state = $3, reviewer = COALESCE($4, reviewer), review_id = COALESCE($5, review_id), updated_at = now()
WHERE server_id = $1 AND revision = $2
`

type UpdateDescriptorStateParams struct {
	ServerID string
	Revision int64
	State    string
	Reviewer *string
	ReviewID *string
}

func (q *Queries) UpdateDescriptorState(ctx context.Context, arg UpdateDescriptorStateParams) error {
	_, err := q.db.Exec(ctx, updateDescriptorState,
		arg.ServerID,
		arg.Revision,
		arg.State,
		arg.Reviewer,
		arg.ReviewID,
	)
	return err
}

const updateGrantBarrier = `-- name: UpdateGrantBarrier :execrows
UPDATE grants SET state = $2, control_receipt_id = $3, policy_epoch = $4, failure_code = $5, revocation_command_id = $6, fenced_at = $7,
    in_flight_calls = $8, unknown_calls = $9, control_state = $10, revoked_at = $11, updated_at = now()
WHERE grant_id = $1 AND state = $12
`

type UpdateGrantBarrierParams struct {
	GrantID             string
	State               string
	ControlReceiptID    *string
	PolicyEpoch         *int64
	FailureCode         *string
	RevocationCommandID *string
	FencedAt            pgtype.Timestamptz
	InFlightCalls       int64
	UnknownCalls        int64
	ControlState        string
	RevokedAt           pgtype.Timestamptz
	ExpectedState       string
}

func (q *Queries) UpdateGrantBarrier(ctx context.Context, arg UpdateGrantBarrierParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGrantBarrier,
		arg.GrantID,
		arg.State,
		arg.ControlReceiptID,
		arg.PolicyEpoch,
		arg.FailureCode,
		arg.RevocationCommandID,
		arg.FencedAt,
		arg.InFlightCalls,
		arg.UnknownCalls,
		arg.ControlState,
		arg.RevokedAt,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
