// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackgroundRequest struct {
	TaskID           string
	Generation       int64
	TaskKind         string
	InputDigest      string
	Input            []byte
	State            string
	WorkerID         *string
	LeaseUntil       pgtype.Timestamptz
	AttemptCount     int32
	ResultRef        *string
	ResultDigest     *string
	FailureCode      *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TenantID         string
	Revision         int64
	ResultProfile    string
	Effects          string
	DispatchID       *string
	AuthorizationRef string
	MaxAttempts      int32
	RetryAt          pgtype.Timestamptz
	CorrelationID    string
	CompletedAt      pgtype.Timestamptz
}

type Descriptor struct {
	ServerID         string
	Revision         int64
	ProtocolVersion  string
	Provenance       string
	DescriptorDigest string
	Tools            []byte
	State            string
	CommandID        string
	RequestDigest    string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Grant struct {
	GrantID            string
	Revision           int64
	TenantID           string
	SubjectType        string
	SubjectID          string
	ServerID           string
	DescriptorRevision int64
	DescriptorDigest   string
	Methods            []string
	Purpose            string
	CostCapCurrency    string
	CostCapAmount      int64
	State              string
	ControlReceiptID   *string
	ExpiresAt          pgtype.Timestamptz
	CommandID          string
	RequestDigest      string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type GrantDecision struct {
	DecisionID    string
	GrantID       string
	FromRevision  int64
	ToRevision    int64
	Decision      string
	Decider       string
	ReasonCode    *string
	CommandID     string
	RequestDigest string
	DecidedAt     pgtype.Timestamptz
}

type Inbox struct {
	EventID           pgtype.UUID
	Consumer          string
	AcceptedAt        pgtype.Timestamptz
	Outcome           string
	AggregateRevision int64
}

type Outbox struct {
	Offset        int64
	Uuid          string
	CreatedAt     pgtype.Timestamp
	Payload       []byte
	Metadata      []byte
	TransactionID interface{}
}

type OutboxOffset struct {
	ConsumerGroup              string
	OffsetAcked                *int64
	LastProcessedTransactionID interface{}
}

type Review struct {
	ReviewID         string
	ServerID         string
	Revision         int64
	DescriptorDigest string
	Reviewer         string
	Decision         string
	ReasonCode       *string
	CommandID        string
	RequestDigest    string
	DecidedAt        pgtype.Timestamptz
}

type Server struct {
	ServerID          string
	TenantID          string
	CanonicalResource string
	Transport         string
	CurrentRevision   int64
	CreatedAt         pgtype.Timestamptz
}

type TaskAttempt struct {
	TaskID      string
	Generation  int64
	Ordinal     int32
	WorkerID    string
	LeasedAt    pgtype.Timestamptz
	LeaseUntil  pgtype.Timestamptz
	Outcome     *string
	SubmittedAt pgtype.Timestamptz
}

type ToolRequest struct {
	CallID             string
	TenantID           string
	GrantID            string
	GrantRevision      int64
	ServerID           string
	DescriptorRevision int64
	Method             string
	ArgumentRef        string
	ArgumentDigest     string
	OperationID        *string
	AttemptID          *string
	State              string
	ControlDispatchID  *string
	ResultRef          *string
	ResultDigest       *string
	FailureCode        *string
	CommandID          string
	RequestDigest      string
	Deadline           pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
